import { Test, TestingModule } from '@nestjs/testing';

import { GlobalWorkspaceOrmManager } from 'src/engine/twenty-orm/global-workspace-datasource/global-workspace-orm.manager';
import { WorkflowTimelineWriterService } from 'src/modules/idda-timeline-writer/services/workflow-timeline-writer.service';
import { type WorkflowTimelineEvent } from 'src/modules/idda-timeline-writer/types/workflow-timeline-event.type';

// Token generated by InjectObjectMetadataRepository(TimelineActivityWorkspaceEntity):
// capitalize(convertClassNameToObjectMetadataName('TimelineActivityWorkspaceEntity'))
// → 'TimelineActivity' + 'Repository' = 'TimelineActivityRepository'
const TIMELINE_ACTIVITY_REPOSITORY_TOKEN = 'TimelineActivityRepository';

const mockExecuteInWorkspaceContext = jest.fn((fn: () => Promise<unknown>) =>
  fn(),
);

const MOCK_GLOBAL_ORM_MANAGER = {
  executeInWorkspaceContext: mockExecuteInWorkspaceContext,
};

const MOCK_EVENT: WorkflowTimelineEvent = {
  workspaceId: 'ws-123',
  workspaceMemberId: 'member-456',
  targetObjectSingularName: 'lead',
  targetRecordId: 'lead-789',
  eventName: 'workflow.lead.assigned',
  properties: { assignedTo: 'member-456' },
};

describe('WorkflowTimelineWriterService', () => {
  let service: WorkflowTimelineWriterService;
  let insertSpy: jest.SpyInstance;

  beforeEach(async () => {
    const mockRepository = {
      insertTimelineActivities: jest.fn().mockResolvedValue(undefined),
    };

    mockExecuteInWorkspaceContext.mockClear();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        WorkflowTimelineWriterService,
        {
          provide: TIMELINE_ACTIVITY_REPOSITORY_TOKEN,
          useValue: mockRepository,
        },
        {
          provide: GlobalWorkspaceOrmManager,
          useValue: MOCK_GLOBAL_ORM_MANAGER,
        },
      ],
    }).compile();

    service = module.get(WorkflowTimelineWriterService);
    insertSpy = mockRepository.insertTimelineActivities;
  });

  describe('write', () => {
    it('inserts a timeline activity for the given event', async () => {
      await service.write(MOCK_EVENT);

      expect(insertSpy).toHaveBeenCalledTimes(1);
      expect(insertSpy).toHaveBeenCalledWith({
        objectSingularName: 'lead',
        workspaceId: 'ws-123',
        payloads: [
          expect.objectContaining({
            name: 'workflow.lead.assigned',
            workspaceMemberId: 'member-456',
            recordId: 'lead-789',
          }),
        ],
      });
    });

    it('does not throw when the repository fails — errors are logged', async () => {
      insertSpy.mockRejectedValue(new Error('DB failure'));

      await expect(service.write(MOCK_EVENT)).resolves.not.toThrow();
    });
  });

  describe('writeMany', () => {
    it('writes all events even when one fails', async () => {
      insertSpy
        .mockRejectedValueOnce(new Error('first fails'))
        .mockResolvedValue(undefined);

      await service.writeMany([
        MOCK_EVENT,
        { ...MOCK_EVENT, targetRecordId: 'other-id' },
      ]);

      expect(insertSpy).toHaveBeenCalledTimes(2);
    });
  });
});
