import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_BY_STANDARD_OBJECT_NAME } from 'src/engine/workspace-manager/twenty-standard-application/constants/search-fields-by-standard-object-name.constant';

export const buildSubscriptionStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'subscription', FieldMetadataType>,
  'context'
>): Record<
  AllStandardObjectFieldName<'subscription'>,
  FlatFieldMetadata
> => ({
  // Base fields
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Subscription record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(msg`The workspace member who last updated the record`),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_BY_STANDARD_OBJECT_NAME[objectName],
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Subscription fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Subscription name (e.g. "IDDA Gold – Sharma Dental 2025")`),
      icon: 'IconFileText',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  plan: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'plan',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Plan`),
      description: i18nLabel(msg`IDDA subscription plan`),
      icon: 'IconPackage',
      isNullable: true,
      options: [
        {
          id: 'fdc4ce66-05e4-4954-a0ec-141ab614232d',
          value: 'BASIC',
          label: i18nLabel(msg`Basic`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'a71f353a-82ff-4a53-833b-f827843ee43d',
          value: 'STANDARD',
          label: i18nLabel(msg`Standard`),
          position: 1,
          color: 'sky',
        },
        {
          id: 'dc04b12c-5962-4061-9ce1-58fb914570f6',
          value: 'GOLD',
          label: i18nLabel(msg`Gold`),
          position: 2,
          color: 'yellow',
        },
        {
          id: '849c02c6-f951-46d5-9665-f812db24c862',
          value: 'PLATINUM',
          label: i18nLabel(msg`Platinum`),
          position: 3,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Current subscription lifecycle status`),
      icon: 'IconProgressCheck',
      isNullable: false,
      defaultValue: "'TRIAL'",
      options: [
        {
          id: 'c07553a1-444e-411d-b8ac-daaeaaaccfce',
          value: 'ACTIVE',
          label: i18nLabel(msg`Active`),
          position: 0,
          color: 'green',
        },
        {
          id: '283fb23c-955e-49c2-adaa-4cb044e303ab',
          value: 'TRIAL',
          label: i18nLabel(msg`Trial`),
          position: 1,
          color: 'blue',
        },
        {
          id: '50f32f21-a00c-4b10-8be1-08efd5bf52cf',
          value: 'PENDING_RENEWAL',
          label: i18nLabel(msg`Pending Renewal`),
          position: 2,
          color: 'yellow',
        },
        {
          id: 'd3ce8af7-3b15-41f4-83db-dd0da71c9962',
          value: 'EXPIRED',
          label: i18nLabel(msg`Expired`),
          position: 3,
          color: 'orange',
        },
        {
          id: '380e3d74-8dec-45cb-9e5d-8a06e2737410',
          value: 'CANCELLED',
          label: i18nLabel(msg`Cancelled`),
          position: 4,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  startDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'startDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Start Date`),
      description: i18nLabel(msg`Date the subscription begins`),
      icon: 'IconCalendarPlus',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  endDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'endDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`End Date`),
      description: i18nLabel(msg`Date the current subscription period ends`),
      icon: 'IconCalendarMinus',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  renewalDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'renewalDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Renewal Date`),
      description: i18nLabel(msg`When this subscription is next due for renewal`),
      icon: 'IconCalendarRepeat',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  billingCycle: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'billingCycle',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Billing Cycle`),
      description: i18nLabel(msg`How often the subscription renews`),
      icon: 'IconRefresh',
      isNullable: true,
      options: [
        {
          id: '351671d2-a92d-4534-a5b7-3a8d17c1285c',
          value: 'MONTHLY',
          label: i18nLabel(msg`Monthly`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'b480099c-9625-4db9-8181-a9d436769755',
          value: 'QUARTERLY',
          label: i18nLabel(msg`Quarterly`),
          position: 1,
          color: 'sky',
        },
        {
          id: '56b61340-b0a8-4ef5-bb6e-3f3da91b627c',
          value: 'ANNUAL',
          label: i18nLabel(msg`Annual`),
          position: 2,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  amount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'amount',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Amount`),
      description: i18nLabel(msg`Subscription fee amount`),
      icon: 'IconCurrencyRupee',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  paymentStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'paymentStatus',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Payment Status`),
      description: i18nLabel(msg`Current payment status for this subscription`),
      icon: 'IconCreditCard',
      isNullable: true,
      options: [
        {
          id: 'f661d612-088f-4955-b6f0-12adbea6019e',
          value: 'PAID',
          label: i18nLabel(msg`Paid`),
          position: 0,
          color: 'green',
        },
        {
          id: '29d4223f-12ee-4d6e-a49c-bd1155edd333',
          value: 'PENDING',
          label: i18nLabel(msg`Pending`),
          position: 1,
          color: 'yellow',
        },
        {
          id: 'a8f2b840-f6f0-48d7-93b5-8ef72244e716',
          value: 'OVERDUE',
          label: i18nLabel(msg`Overdue`),
          position: 2,
          color: 'red',
        },
        {
          id: '651b536f-1622-400d-9a73-ecf8a0577159',
          value: 'WAIVED',
          label: i18nLabel(msg`Waived`),
          position: 3,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relations
  clinic: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'clinic',
      label: i18nLabel(msg`Clinic`),
      description: i18nLabel(msg`The clinic this subscription belongs to`),
      icon: 'IconBuildingHospital',
      isNullable: true,
      targetObjectName: 'company',
      targetFieldName: 'subscriptions',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'clinicId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  doctor: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'doctor',
      label: i18nLabel(msg`Doctor`),
      description: i18nLabel(msg`The primary doctor contact for this subscription`),
      icon: 'IconStethoscope',
      isNullable: true,
      targetObjectName: 'person',
      targetFieldName: 'subscriptions',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'doctorId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  assignedEmployee: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'assignedEmployee',
      label: i18nLabel(msg`Assigned Employee`),
      description: i18nLabel(msg`IDDA employee managing this subscription`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'managedSubscriptions',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'assignedEmployeeId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
