import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT } from 'src/engine/metadata-modules/object-metadata/constants/standard-relation-field-properties.constant';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_BY_STANDARD_OBJECT_NAME } from 'src/engine/workspace-manager/twenty-standard-application/constants/search-fields-by-standard-object-name.constant';

export const buildLeadStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'lead', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'lead'>, FlatFieldMetadata> => ({
  // Base fields
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Lead record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(msg`The workspace member who last updated the record`),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_BY_STANDARD_OBJECT_NAME[objectName],
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // MedLeads import fields
  clinicName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'clinicName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Clinic Name`),
      description: i18nLabel(msg`Name of the clinic from MedLeads`),
      icon: 'IconBuildingHospital',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  doctorName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'doctorName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Doctor Name`),
      description: i18nLabel(msg`Primary doctor's name from MedLeads`),
      icon: 'IconStethoscope',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  specialization: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'specialization',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Specialization`),
      description: i18nLabel(msg`Medical specialization as listed on Google Maps`),
      icon: 'IconHeartbeat',
      isNullable: true,
      options: [
        { id: 'a1b2c3d4-0001-4001-8001-000000000001', value: 'DENTIST', label: i18nLabel(msg`Dentist`), position: 0, color: 'blue' },
        { id: 'a1b2c3d4-0002-4002-8002-000000000002', value: 'DERMATOLOGIST', label: i18nLabel(msg`Dermatologist`), position: 1, color: 'sky' },
        { id: 'a1b2c3d4-0003-4003-8003-000000000003', value: 'PAEDIATRICIAN', label: i18nLabel(msg`Paediatrician`), position: 2, color: 'green' },
        { id: 'a1b2c3d4-0004-4004-8004-000000000004', value: 'GENERAL_PHYSICIAN', label: i18nLabel(msg`General Physician`), position: 3, color: 'turquoise' },
        { id: 'a1b2c3d4-0005-4005-8005-000000000005', value: 'ENT', label: i18nLabel(msg`ENT`), position: 4, color: 'purple' },
        { id: 'a1b2c3d4-0006-4006-8006-000000000006', value: 'COSMETOLOGIST', label: i18nLabel(msg`Cosmetologist`), position: 5, color: 'pink' },
        { id: 'a1b2c3d4-0007-4007-8007-000000000007', value: 'PLASTIC_SURGEON', label: i18nLabel(msg`Plastic Surgeon`), position: 6, color: 'red' },
        { id: 'a1b2c3d4-0008-4008-8008-000000000008', value: 'TRICHOLOGIST', label: i18nLabel(msg`Trichologist`), position: 7, color: 'yellow' },
        { id: 'a1b2c3d4-0009-4009-8009-000000000009', value: 'HOSPITAL', label: i18nLabel(msg`Hospital`), position: 8, color: 'orange' },
        { id: 'a1b2c3d4-000a-400a-800a-00000000000a', value: 'CLINIC', label: i18nLabel(msg`Clinic`), position: 9, color: 'gray' },
        { id: 'a1b2c3d4-000b-400b-800b-00000000000b', value: 'OTHER', label: i18nLabel(msg`Other`), position: 10, color: 'gray' },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  otherDoctors: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'otherDoctors',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Other Doctors`),
      description: i18nLabel(msg`Other doctors listed at this clinic`),
      icon: 'IconUsers',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  phone: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'phone',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Phone`),
      description: i18nLabel(msg`Clinic phone number from MedLeads`),
      icon: 'IconPhone',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  address: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'address',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Address`),
      description: i18nLabel(msg`Street address from MedLeads`),
      icon: 'IconMapPin',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  town: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'town',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Town`),
      description: i18nLabel(msg`Town from MedLeads`),
      icon: 'IconBuilding',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  city: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'city',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`City`),
      description: i18nLabel(msg`City from MedLeads`),
      icon: 'IconBuilding',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  state: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'state',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`State`),
      description: i18nLabel(msg`State from MedLeads`),
      icon: 'IconMap2',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  category: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'category',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Category`),
      description: i18nLabel(msg`Clinic category as listed on Google Maps`),
      icon: 'IconCategory',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  rating: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'rating',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Rating`),
      description: i18nLabel(msg`Google Maps rating (0–5)`),
      icon: 'IconStar',
      isNullable: true,
      settings: {
        decimals: 1,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reviews: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reviews',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Reviews`),
      description: i18nLabel(msg`Number of Google Maps reviews`),
      icon: 'IconMessageCircle',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  website: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'website',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Website`),
      description: i18nLabel(msg`Clinic website from MedLeads`),
      icon: 'IconLink',
      isNullable: true,
      settings: {
        maxNumberOfValues: 1,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  mapsUrl: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'mapsUrl',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Maps URL`),
      description: i18nLabel(msg`Google Maps link for this clinic`),
      icon: 'IconMapPin',
      isNullable: true,
      settings: {
        maxNumberOfValues: 1,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  latitude: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'latitude',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Latitude`),
      description: i18nLabel(msg`Geographic latitude coordinate`),
      icon: 'IconMap2',
      isNullable: true,
      settings: {
        decimals: 6,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  longitude: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'longitude',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Longitude`),
      description: i18nLabel(msg`Geographic longitude coordinate`),
      icon: 'IconMap2',
      isNullable: true,
      settings: {
        decimals: 6,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  extractedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'extractedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Extracted At`),
      description: i18nLabel(msg`When this record was scraped from MedLeads`),
      icon: 'IconCalendarDown',
      isNullable: true,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // CRM-specific fields
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Current stage in the lead qualification pipeline`),
      icon: 'IconProgressCheck',
      isNullable: false,
      defaultValue: "'NEW'",
      options: [
        {
          id: 'de76b199-9534-4c26-81b2-5a52efe1b57d',
          value: 'NEW',
          label: i18nLabel(msg`New`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'fab50036-cd01-4182-b87f-0894b294b787',
          value: 'ASSIGNED',
          label: i18nLabel(msg`Assigned`),
          position: 1,
          color: 'purple',
        },
        {
          id: '32450f44-faae-4f18-a860-b4daa847dc53',
          value: 'CONTACTED',
          label: i18nLabel(msg`Contacted`),
          position: 2,
          color: 'sky',
        },
        {
          id: '1d1260a8-889f-401c-9161-c83faaeb9764',
          value: 'INTERESTED',
          label: i18nLabel(msg`Interested`),
          position: 3,
          color: 'yellow',
        },
        {
          id: 'afe67512-f570-48f0-bd20-72616154ac4a',
          value: 'CONVERTED',
          label: i18nLabel(msg`Converted`),
          position: 4,
          color: 'green',
        },
        {
          id: '29068f81-1414-4047-91bb-d71e1b099d9c',
          value: 'REJECTED',
          label: i18nLabel(msg`Rejected`),
          position: 5,
          color: 'red',
        },
        {
          id: '24b554c6-e8e2-4d97-8d82-162791d3a655',
          value: 'DUPLICATE',
          label: i18nLabel(msg`Duplicate`),
          position: 6,
          color: 'gray',
        },
        {
          id: 'f3c4d5e6-1234-5678-abcd-ef0000000001',
          value: 'FOLLOW_UP_NEEDED',
          label: i18nLabel(msg`Follow-up Needed`),
          position: 7,
          color: 'orange',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  priority: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'priority',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Priority`),
      description: i18nLabel(msg`Lead priority level`),
      icon: 'IconFlag',
      isNullable: true,
      options: [
        {
          id: '6acd6895-415e-44bb-b257-64fabfa5e285',
          value: 'LOW',
          label: i18nLabel(msg`Low`),
          position: 0,
          color: 'blue',
        },
        {
          id: '602f9a96-19a3-4b15-a449-b71285fabdf1',
          value: 'MEDIUM',
          label: i18nLabel(msg`Medium`),
          position: 1,
          color: 'yellow',
        },
        {
          id: '83d86b9d-40b0-4470-9bdf-fd203d27123a',
          value: 'HIGH',
          label: i18nLabel(msg`High`),
          position: 2,
          color: 'red',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  source: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'source',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source`),
      description: i18nLabel(msg`MedLeads batch or campaign that imported this record`),
      icon: 'IconDatabase',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  importedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'importedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Imported At`),
      description: i18nLabel(msg`When this lead was imported into the CRM`),
      icon: 'IconCloudDownload',
      isNullable: true,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  nextFollowUpDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'nextFollowUpDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Next Follow-Up Date`),
      description: i18nLabel(msg`Scheduled date for the next follow-up action on this lead`),
      icon: 'IconCalendarCheck',
      isNullable: true,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relations
  clinic: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'clinic',
      label: i18nLabel(msg`Clinic`),
      description: i18nLabel(msg`The clinic this lead belongs to (set on conversion)`),
      icon: 'IconBuildingHospital',
      isNullable: true,
      targetObjectName: 'company',
      targetFieldName: 'leads',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'clinicId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  doctor: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'doctor',
      label: i18nLabel(msg`Doctor`),
      description: i18nLabel(msg`The doctor this lead belongs to (set on conversion)`),
      icon: 'IconStethoscope',
      isNullable: true,
      targetObjectName: 'person',
      targetFieldName: 'leads',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'doctorId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  taskTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'taskTargets',
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.taskTarget.label,
      ),
      description: i18nLabel(msg`Tasks tied to the lead`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.taskTarget.icon,
      isUIEditable: false,
      isNullable: true,
      targetObjectName: 'taskTarget',
      targetFieldName: 'targetLead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  noteTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'noteTargets',
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.noteTarget.label,
      ),
      description: i18nLabel(msg`Notes tied to the lead`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.noteTarget.icon,
      isUIEditable: false,
      isNullable: true,
      targetObjectName: 'noteTarget',
      targetFieldName: 'targetLead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  attachments: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'attachments',
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.attachment.label,
      ),
      description: i18nLabel(msg`Attachments linked to the lead`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.attachment.icon,
      isNullable: true,
      targetObjectName: 'attachment',
      targetFieldName: 'targetLead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.timelineActivity.label,
      ),
      description: i18nLabel(msg`Timeline activities linked to the lead`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.timelineActivity.icon,
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetLead',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  assignedTo: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'assignedTo',
      label: i18nLabel(msg`Assigned To`),
      description: i18nLabel(msg`IDDA employee responsible for this lead`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'assignedLeads',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'assignedToId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
