import { msg } from '@lingui/core/macro';

import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_BY_STANDARD_OBJECT_NAME } from 'src/engine/workspace-manager/twenty-standard-application/constants/search-fields-by-standard-object-name.constant';

export const buildTeamMemberStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'teamMember', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'teamMember'>, FlatFieldMetadata> => ({
  // ── Base fields ────────────────────────────────────────────────────────────
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: { source: "'MANUAL'", name: "'System'", workspaceMemberId: null },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(msg`The workspace member who last updated the record`),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: { source: "'MANUAL'", name: "'System'", workspaceMemberId: null },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconSearch',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_BY_STANDARD_OBJECT_NAME[objectName],
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ── Identity ───────────────────────────────────────────────────────────────
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.FULL_NAME,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Employee full name`),
      icon: 'IconUser',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  workEmail: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'workEmail',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Work Email`),
      description: i18nLabel(msg`Employee work email address (normalized, unique per workspace)`),
      icon: 'IconMail',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  phone: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'phone',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Phone`),
      description: i18nLabel(msg`Employee phone number`),
      icon: 'IconPhone',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ── Role and department ────────────────────────────────────────────────────
  roleLabel: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'roleLabel',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Role`),
      description: i18nLabel(msg`Current IDDA role label (synced from RBAC)`),
      icon: 'IconShieldCheck',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  department: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'department',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Department`),
      description: i18nLabel(msg`Department derived from the employee's primary role`),
      icon: 'IconBuildingCommunity',
      isNullable: true,
      options: [
        { id: 'e4e5f6a7-0001-4001-8001-000000000101', value: 'ADMINISTRATION', label: i18nLabel(msg`Administration`), position: 0, color: 'gray' },
        { id: 'e4e5f6a7-0002-4002-8002-000000000102', value: 'LEADERSHIP', label: i18nLabel(msg`Leadership`), position: 1, color: 'blue' },
        { id: 'e4e5f6a7-0003-4003-8003-000000000103', value: 'TECHNOLOGY', label: i18nLabel(msg`Technology`), position: 2, color: 'purple' },
        { id: 'e4e5f6a7-0004-4004-8004-000000000104', value: 'HUMAN_RESOURCES', label: i18nLabel(msg`Human Resources`), position: 3, color: 'turquoise' },
        { id: 'e4e5f6a7-0005-4005-8005-000000000105', value: 'SALES', label: i18nLabel(msg`Sales`), position: 4, color: 'green' },
        { id: 'e4e5f6a7-0006-4006-8006-000000000106', value: 'OPERATIONS', label: i18nLabel(msg`Operations`), position: 5, color: 'orange' },
        { id: 'e4e5f6a7-0007-4007-8007-000000000107', value: 'RESEARCH', label: i18nLabel(msg`Research`), position: 6, color: 'sky' },
        { id: 'e4e5f6a7-0008-4008-8008-000000000108', value: 'BUSINESS_DEVELOPMENT', label: i18nLabel(msg`Business Development`), position: 7, color: 'yellow' },
        { id: 'e4e5f6a7-0009-4009-8009-000000000109', value: 'BRAND_COMMUNICATION', label: i18nLabel(msg`Brand Communication`), position: 8, color: 'pink' },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ── Employment ─────────────────────────────────────────────────────────────
  employmentStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'employmentStatus',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Employment Status`),
      description: i18nLabel(msg`Current employment status`),
      icon: 'IconProgressCheck',
      isNullable: false,
      defaultValue: "'ACTIVE'",
      options: [
        { id: 'e5e6f7a8-0001-4001-8001-000000000201', value: 'ACTIVE', label: i18nLabel(msg`Active`), position: 0, color: 'green' },
        { id: 'e5e6f7a8-0002-4002-8002-000000000202', value: 'INACTIVE', label: i18nLabel(msg`Inactive`), position: 1, color: 'gray' },
        { id: 'e5e6f7a8-0003-4003-8003-000000000203', value: 'ON_LEAVE', label: i18nLabel(msg`On Leave`), position: 2, color: 'yellow' },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  employeeType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'employeeType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Employee Type`),
      description: i18nLabel(msg`Type of employment arrangement`),
      icon: 'IconBriefcase',
      isNullable: true,
      options: [
        { id: 'e6e7f8a9-0001-4001-8001-000000000301', value: 'FULL_TIME', label: i18nLabel(msg`Full-time`), position: 0, color: 'blue' },
        { id: 'e6e7f8a9-0002-4002-8002-000000000302', value: 'PART_TIME', label: i18nLabel(msg`Part-time`), position: 1, color: 'sky' },
        { id: 'e6e7f8a9-0003-4003-8003-000000000303', value: 'CONTRACTOR', label: i18nLabel(msg`Contractor`), position: 2, color: 'orange' },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  joiningDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'joiningDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Joining Date`),
      description: i18nLabel(msg`Date the employee joined IDDA (use this to calculate tenure)`),
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  location: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'location',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Location`),
      description: i18nLabel(msg`Employee work location or city`),
      icon: 'IconMapPin',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ── Cross-schema links (plain UUIDs — not workspace RELATION fields) ────────
  workspaceMemberId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'workspaceMemberId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Workspace Member ID`),
      description: i18nLabel(msg`Unique link to the corresponding workspace member record`),
      icon: 'IconUserCircle',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  userId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'userId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`User ID`),
      description: i18nLabel(msg`Auth user ID linked to this employee record`),
      icon: 'Icon123',
      isNullable: true,
      isUIEditable: false,
      isSystem: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ── Sync metadata ──────────────────────────────────────────────────────────
  source: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'source',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source`),
      description: i18nLabel(msg`How this record was created (e.g. CRM User Sync)`),
      icon: 'IconDatabase',
      isNullable: true,
      isUIEditable: false,
      defaultValue: "'CRM User Sync'",
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lastSyncedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lastSyncedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last Synced At`),
      description: i18nLabel(msg`When this record was last synced from workspace member data`),
      icon: 'IconRefresh',
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // ── Reporting manager (plain UUID text — no bidirectional relation) ────────
  reportingManager: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reportingManager',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Reporting Manager ID`),
      description: i18nLabel(msg`workspaceMemberId of the employee's reporting manager`),
      icon: 'IconUserUp',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
