import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_BY_STANDARD_OBJECT_NAME } from 'src/engine/workspace-manager/twenty-standard-application/constants/search-fields-by-standard-object-name.constant';

export const buildVisitStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'visit', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'visit'>, FlatFieldMetadata> => ({
  // Base fields
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Visit record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(msg`The workspace member who last updated the record`),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_BY_STANDARD_OBJECT_NAME[objectName],
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Visit core fields
  visitDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'visitDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Visit Date`),
      description: i18nLabel(msg`Date and time of the visit`),
      icon: 'IconCalendar',
      isNullable: false,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  visitNotes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'visitNotes',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Visit Notes`),
      description: i18nLabel(msg`Notes taken during the visit`),
      icon: 'IconNotes',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // GPS fields
  latitude: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'latitude',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Latitude`),
      description: i18nLabel(msg`GPS latitude coordinate at time of visit`),
      icon: 'IconMapPin',
      isNullable: true,
      isUIEditable: false,
      settings: {
        decimals: 6,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  longitude: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'longitude',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Longitude`),
      description: i18nLabel(msg`GPS longitude coordinate at time of visit`),
      icon: 'IconMapPin',
      isNullable: true,
      isUIEditable: false,
      settings: {
        decimals: 6,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  visitAddress: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'visitAddress',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Visit Address`),
      description: i18nLabel(msg`Reverse-geocoded address at time of visit`),
      icon: 'IconMap',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Selfie fields
  selfie: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'selfie',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Selfie`),
      description: i18nLabel(msg`Stored path of the visit selfie image`),
      icon: 'IconCamera',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  selfieHash: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'selfieHash',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Selfie Hash`),
      description: i18nLabel(msg`SHA-256 hash of selfie for duplicate detection`),
      icon: 'IconFingerprint',
      isNullable: true,
      isSystem: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  selfieStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'selfieStatus',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Selfie Status`),
      description: i18nLabel(msg`Quality status of the captured selfie`),
      icon: 'IconUserScan',
      isNullable: true,
      defaultValue: "'MISSING'",
      options: [
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-010000000001',
          value: 'CLEAR',
          label: i18nLabel(msg`Clear`),
          position: 0,
          color: 'green',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-010000000002',
          value: 'FACE_NOT_CLEAR',
          label: i18nLabel(msg`Face Not Clear`),
          position: 1,
          color: 'orange',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-010000000003',
          value: 'MISSING',
          label: i18nLabel(msg`Missing`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // GPS verification
  gpsAccuracy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'gpsAccuracy',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`GPS Accuracy (m)`),
      description: i18nLabel(msg`GPS accuracy radius in metres`),
      icon: 'IconRadar',
      isNullable: true,
      isUIEditable: false,
      settings: {
        decimals: 2,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  distanceFromClinic: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'distanceFromClinic',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Distance from Clinic (m)`),
      description: i18nLabel(msg`Computed distance in metres from the clinic`),
      icon: 'IconRuler',
      isNullable: true,
      isUIEditable: false,
      settings: {
        decimals: 2,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  locationStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'locationStatus',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Location Status`),
      description: i18nLabel(msg`Whether the employee was within clinic geofence`),
      icon: 'IconShieldCheck',
      isNullable: true,
      isUIEditable: false,
      options: [
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-020000000001',
          value: 'WITHIN_RANGE',
          label: i18nLabel(msg`Within Range`),
          position: 0,
          color: 'green',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-020000000002',
          value: 'OUTSIDE_RANGE',
          label: i18nLabel(msg`Outside Range`),
          position: 1,
          color: 'red',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-020000000003',
          value: 'SUSPICIOUS',
          label: i18nLabel(msg`Suspicious Location`),
          position: 2,
          color: 'orange',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Capture metadata
  liveCameraCapture: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'liveCameraCapture',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Live Camera Capture`),
      description: i18nLabel(msg`Whether photo was taken live from camera`),
      icon: 'IconVideo',
      isNullable: false,
      isUIEditable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  imageReused: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'imageReused',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Image Reused`),
      description: i18nLabel(msg`Whether a previously uploaded image was reused`),
      icon: 'IconCopy',
      isNullable: false,
      isUIEditable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Verification results
  verificationScore: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'verificationScore',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Verification Score`),
      description: i18nLabel(msg`Score 0-100 computed from verification checks`),
      icon: 'IconStar',
      isNullable: true,
      isUIEditable: false,
      settings: {
        decimals: 0,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  verificationStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'verificationStatus',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Verification Status`),
      description: i18nLabel(msg`Overall verification outcome`),
      icon: 'IconShield',
      isNullable: true,
      isUIEditable: false,
      defaultValue: "'UNVERIFIED'",
      options: [
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-030000000001',
          value: 'VERIFIED',
          label: i18nLabel(msg`Verified`),
          position: 0,
          color: 'green',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-030000000002',
          value: 'PARTIALLY_VERIFIED',
          label: i18nLabel(msg`Partially Verified`),
          position: 1,
          color: 'yellow',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-030000000003',
          value: 'UNVERIFIED',
          label: i18nLabel(msg`Unverified`),
          position: 2,
          color: 'red',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-030000000004',
          value: 'NEEDS_REVIEW',
          label: i18nLabel(msg`Needs Review`),
          position: 3,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reviewDecision: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reviewDecision',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Review Decision`),
      description: i18nLabel(msg`Manager review outcome for this visit`),
      icon: 'IconChecklist',
      isNullable: true,
      defaultValue: "'PENDING'",
      options: [
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-040000000001',
          value: 'APPROVED',
          label: i18nLabel(msg`Approved`),
          position: 0,
          color: 'green',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-040000000002',
          value: 'REJECTED',
          label: i18nLabel(msg`Rejected`),
          position: 1,
          color: 'red',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-040000000003',
          value: 'PENDING',
          label: i18nLabel(msg`Pending`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  reviewComment: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reviewComment',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Review Comment`),
      description: i18nLabel(msg`Manager comment when approving or rejecting this visit`),
      icon: 'IconMessage',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Device / source
  deviceIdentifier: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deviceIdentifier',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Device Identifier`),
      description: i18nLabel(msg`Identifier of the device used to capture the selfie`),
      icon: 'IconDeviceMobile',
      isNullable: true,
      isSystem: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  captureSource: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'captureSource',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Capture Source`),
      description: i18nLabel(msg`Method used to capture the selfie`),
      icon: 'IconCamera',
      isNullable: true,
      isUIEditable: false,
      options: [
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-050000000001',
          value: 'CRM_MOBILE_CAMERA',
          label: i18nLabel(msg`CRM Mobile Camera`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'a0b1c2d3-e4f5-6789-abcd-050000000002',
          value: 'CRM_WEB_CAMERA',
          label: i18nLabel(msg`CRM Web Camera`),
          position: 1,
          color: 'sky',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  clinicPhoto: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'clinicPhoto',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Clinic Photo`),
      description: i18nLabel(msg`Stored path of the clinic exterior photo`),
      icon: 'IconPhoto',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  selfiePhoto: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'selfiePhoto',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Selfie Photo`),
      description: i18nLabel(msg`Stored path of the agent selfie taken during check-in`),
      icon: 'IconCamera',
      isNullable: true,
      isUIEditable: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relations
  clinic: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'clinic',
      label: i18nLabel(msg`Clinic`),
      description: i18nLabel(msg`The clinic visited`),
      icon: 'IconBuildingHospital',
      isNullable: true,
      targetObjectName: 'company',
      targetFieldName: 'visits',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'clinicId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  employee: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'employee',
      label: i18nLabel(msg`Employee`),
      description: i18nLabel(msg`The IDDA employee who made the visit`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'visits',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'employeeId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
