import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import {
  createStandardViewFieldFlatMetadata,
  type CreateStandardViewFieldArgs,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardLeadViewFields = (
  args: Omit<CreateStandardViewFieldArgs<'lead'>, 'context'>,
): Record<string, FlatViewField> => {
  return {
    // allLeads view fields
    allLeadsClinicName: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'allLeads',
        viewFieldName: 'clinicName',
        fieldName: 'clinicName',
        position: 0,
        isVisible: true,
        size: 200,
      },
    }),
    allLeadsDoctorName: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'allLeads',
        viewFieldName: 'doctorName',
        fieldName: 'doctorName',
        position: 1,
        isVisible: true,
        size: 180,
      },
    }),
    allLeadsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'allLeads',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 2,
        isVisible: true,
        size: 120,
      },
    }),
    allLeadsPriority: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'allLeads',
        viewFieldName: 'priority',
        fieldName: 'priority',
        position: 3,
        isVisible: true,
        size: 120,
      },
    }),
    allLeadsCity: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'allLeads',
        viewFieldName: 'city',
        fieldName: 'city',
        position: 4,
        isVisible: true,
        size: 140,
      },
    }),
    allLeadsPhone: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'allLeads',
        viewFieldName: 'phone',
        fieldName: 'phone',
        position: 5,
        isVisible: true,
        size: 150,
      },
    }),
    allLeadsAssignedTo: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'allLeads',
        viewFieldName: 'assignedTo',
        fieldName: 'assignedTo',
        position: 6,
        isVisible: true,
        size: 150,
      },
    }),
    allLeadsRating: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'allLeads',
        viewFieldName: 'rating',
        fieldName: 'rating',
        position: 7,
        isVisible: true,
        size: 100,
      },
    }),

    // leadRecordPageFields — leadInfo group
    leadRecordPageFieldsClinicName: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'clinicName',
        fieldName: 'clinicName',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'leadInfo',
      },
    }),
    leadRecordPageFieldsDoctorName: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'doctorName',
        fieldName: 'doctorName',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'leadInfo',
      },
    }),
    leadRecordPageFieldsSpecialization: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'specialization',
        fieldName: 'specialization',
        position: 2,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'leadInfo',
      },
    }),
    leadRecordPageFieldsOtherDoctors: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'otherDoctors',
        fieldName: 'otherDoctors',
        position: 3,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'leadInfo',
      },
    }),
    leadRecordPageFieldsPhone: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'phone',
        fieldName: 'phone',
        position: 4,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'leadInfo',
      },
    }),

    // leadRecordPageFields — location group
    leadRecordPageFieldsAddress: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'address',
        fieldName: 'address',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'location',
      },
    }),
    leadRecordPageFieldsTown: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'town',
        fieldName: 'town',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'location',
      },
    }),
    leadRecordPageFieldsCity: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'city',
        fieldName: 'city',
        position: 2,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'location',
      },
    }),
    leadRecordPageFieldsState: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'state',
        fieldName: 'state',
        position: 3,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'location',
      },
    }),
    leadRecordPageFieldsRating: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'rating',
        fieldName: 'rating',
        position: 4,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'location',
      },
    }),
    leadRecordPageFieldsReviews: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'reviews',
        fieldName: 'reviews',
        position: 5,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'location',
      },
    }),
    leadRecordPageFieldsCategory: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'category',
        fieldName: 'category',
        position: 6,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'location',
      },
    }),

    // leadRecordPageFields — crm group
    leadRecordPageFieldsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsPriority: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'priority',
        fieldName: 'priority',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsSource: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'source',
        fieldName: 'source',
        position: 2,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsImportedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'importedAt',
        fieldName: 'importedAt',
        position: 3,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsWebsite: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'website',
        fieldName: 'website',
        position: 4,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsMapsUrl: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'mapsUrl',
        fieldName: 'mapsUrl',
        position: 5,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsExtractedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'extractedAt',
        fieldName: 'extractedAt',
        position: 6,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsClinic: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'clinic',
        fieldName: 'clinic',
        position: 7,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsDoctor: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'doctor',
        fieldName: 'doctor',
        position: 8,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsAssignedTo: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'assignedTo',
        fieldName: 'assignedTo',
        position: 9,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsTaskTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'taskTargets',
        fieldName: 'taskTargets',
        position: 10,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),
    leadRecordPageFieldsNoteTargets: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'noteTargets',
        fieldName: 'noteTargets',
        position: 11,
        isVisible: false,
        size: 150,
        viewFieldGroupName: 'crm',
      },
    }),

    // leadRecordPageFields — system group
    leadRecordPageFieldsCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 0,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'system',
      },
    }),
    leadRecordPageFieldsCreatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'lead',
      context: {
        viewName: 'leadRecordPageFields',
        viewFieldName: 'createdBy',
        fieldName: 'createdBy',
        position: 1,
        isVisible: true,
        size: 150,
        viewFieldGroupName: 'system',
      },
    }),
  };
};
